name: tekartik_lints
description: Common dart lints
version: 0.4.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  lints:

dev_dependencies:
  dev_test:
  path:
  test: '>=1.24.4'
  yaml:

dependency_overrides:
# lints: '>=2.0.0'/
