name: tekartik_lints
description: Common dart lints
version: 0.4.2
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  lints: ">=5.1.1"

dev_dependencies:
  process_run: ">=1.2.1+1"
  dev_build: ">=1.1.2"
  path: ">=1.9.0"
  test: '>=1.24.4'
  yaml: ">=3.1.2"
dependency_overrides:
  lints: '>=6.0.0'

resolution: workspace

