name: tekartik_lints
description: Common dart lints
version: 0.4.2
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  lints: '>=2.1.1'

dev_dependencies:
  dev_test: '>=0.16.2'
  path:
  test: '>=1.24.4'
  yaml:

dependency_overrides:
# lints: '>=2.0.0'/
