name: tekartik_lints
description: Common dart lints
version: 0.4.2
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  lints: '>=2.1.1'
  dart_flutter_team_lints: '>=0.1.0'
  very_good_analysis: '>=2.3.0'
dev_dependencies:
  process_run: '>=1.2.0'
  dev_build: '>=1.0.0'
  path:
  test: '>=1.24.4'
  yaml:

dependency_overrides:
# lints: '>=2.0.0'/
