name: tekartik_lints
description: Common dart lints
version: 0.2.1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  lints:

dev_dependencies:
  test: '>=1.16.0'
  pedantic:
  yaml:
  path:

dependency_overrides:
  # lints: '>=2.0.0'