name: tekartik_lints
description: Common dart lints
version: 0.3.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  dart_flutter_team_lints:

dev_dependencies:
  dev_test:
  path:
  test: '>=1.16.0'
  yaml:

dependency_overrides:
# lints: '>=2.0.0'