name: tekartik_lints
description: Common dart lints
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  lints: ">=5.1.1"
  tekartik_core:
    git:
      url: https://github.com/tekartik/common.dart
      # tag_pattern: "tekartik_core/v{{version}}"
      path: packages/core
    version: ^0.1.0
dev_dependencies:
  process_run: ">=1.2.1+1"
  dev_build: ">=1.1.2"
  path: ">=1.9.0"
  test: '>=1.24.4'
  yaml: ">=3.1.2"

resolution: workspace

