name: tekartik_lints_support
description: Tekartik lints support
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  dart_flutter_team_lints: '>=0.1.0'
  very_good_analysis: '>=2.3.0'
  fs_shim: ">=2.3.3+1"
  dev_build: ">=1.1.2"
  path: ">=1.9.0"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
  tekartik_prj_tktools:
    git:
      url: https://github.com/tekartikprj/tktools.git
      ref: dart3a
      path: packages/prj_tktools
  # path: ^1.8.0

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"

dependency_overrides:
  dart_flutter_team_lints: '>=3.5.1'
  very_good_analysis: '>=7.0.0'
resolution: workspace

